### ISSUE TITLE
pls can you help me i get this error !!

### ISSUE THREAD

**Issue by wolfayoub** [davidteather/TikTokBot#14]
Traceback (most recent call last):
  File "C:\Users\doubl\Desktop\TikTokBot-master\tiktokbot.py", line 123, in <module>
    res = api.byHashtag(x, count=count, custom_did=did)
  File "C:\Users\doubl\AppData\Local\Programs\Python\Python38\lib\site-packages\TikTokApi\tiktok.py", line 711, in byHashtag
    for t in res["itemList"]:
KeyError: 'itemList'

**Comment by davidteather** [comment]
Sorry for the late response, should have been fixed by now. If you run into issues with `api.XXXXXX` method calls file issues on [TikTok-Api](https://github.com/davidteather/TikTok-Api)
