### ISSUE TITLE
[BUG] HELP - secs = float(secsval) ValueError: could not convert string to float: ''

### ISSUE THREAD

**Issue by JustDhan** [davidteather/TikTokBot#19]
I installed playwright, all module requests, i flaged to true API_Endpoint in the API "tiktok.py" file and finally solved the Hashtag CAPTHA ERROR
After thate the new issue became when start the script from Tiktokbot.py

Traceback (most recent call last):
  File "C:\Users\X\Desktop\TikTokbot\tiktokbot.py", line 152, in <module>
    vidLength = getLength('downloaded/' + str(x) + ".mp4")
  File "C:\Users\X\Desktop\TikTokbot\tiktokbot.py", line 23, in getLength
    secs = float(secsval)
ValueError: could not convert string to float: ''

Pip verssion 20.2
Python version 3.9

Do you suggest a specific version of FFMPEG,PLAYWRIGHT or PYTHON?

**Comment by JustDhan** [comment]
Solved issue simply by changing the search hashtag
