### ISSUE TITLE
ImportError: cannot import name 'sync_playwright' from 'playwright'

### ISSUE THREAD

**Issue by NecroBoy** [davidteather/TikTokBot#20]
`C:\Users\NecroBoy\TikTokBot>python tiktokbot.py
Traceback (most recent call last):
  File "C:\Users\NecroBoy\TikTokBot\tiktokbot.py", line 7, in <module>
    from TikTokApi import TikTokApi
  File "C:\Users\NecroBoy\AppData\Local\Programs\Python\Python39\lib\site-packages\TikTokApi\__init__.py", line 1, in <module>
    from TikTokApi.tiktok import TikTokApi
  File "C:\Users\NecroBoy\AppData\Local\Programs\Python\Python39\lib\site-packages\TikTokApi\tiktok.py", line 7, in <module>
    from playwright import sync_playwright
ImportError: cannot import name 'sync_playwright' from 'playwright' (C:\Users\NecroBoy\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\__init__.py)`

Hello! How to fix this error?

**Comment by NecroBoy** [comment]
Fixed after updating playwright
use `pip install TikTokApi playwright --upgrade` if same error

**Comment by NecroBoy** [comment]
Closed
