### ISSUE TITLE
ERROR:root:Tiktok wants to display a catcha. 

### ISSUE THREAD

**Issue by heiver13** [davidteather/TikTokBot#23]
ERROR:root:Tiktok wants to display a catcha. Response is:
{"code":"10000","from":"","type":"verify","version":"","region":"va","subtype":"slide","detail":"bghAdiQWAooU6FchmbRx0rL2SN-YruF9XFp7egH5yZBgVLpmJyM*Tk27utHCOh2m8t3xBuCjeRQGZYGKLJqMF5ugIAWqOZ7MrIRSNpXkMwN-tHyfWZ34XrvaR1rfHdKFil3Ha0lCYuF904AqU2cXczq3ijRmFJyZ2u22AprYekDG2j*akHuV4XcH2MDUBKtCWYPIzJ-wqqBSqd78SYsJm7ZDRW6awAS5*eA1FtzSuWBkFLuGiIQMRKyG0uqhhBSfdAgbKhXSPispzGYXMdsj314Vakf5ftEmxKYs7fF7RQ4WBeH-TzZaq-BgLaVHBdlAah9CMcRTPMB7hYCZk8sLRB1dAtLJ7GpV79GhnChL6ljOA6XJAfoMxTBlKVuz-s4oTkKikAAlxRP8bNr1y5OByigLEqGc3n3YamSbbJraHA..","verify_event":"","fp":"verify_mZCnHTecLgmXuUGEZmQUiARpZqzazKofUjzMCsRI","scene":"","verify_ticket":"","channel_mobile":"","sms_content":"","mobile":"","email":""}
ERROR:root:{'tt_webid': '2866585807669016319', 'tt_webid_v2': '2866585807669016319', 'tt_csrf_token': 'OyvfhaglRtQDitVB'}
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\TikTokBot-master\tiktokbot.py", line 127, in <module>
    res = api.byHashtag(x, count=count, custom_did=did)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\lib\site-packages\TikTokApi\tiktok.py", line 915, in by_hashtag
    res = self.getData(url=api_url, **kwargs)
  File "C:\Users\lenovo\AppData\Local\Programs\Python\lib\site-packages\TikTokApi\tiktok.py", line 270, in get_data
    raise TikTokCaptchaError()
TikTokApi.exceptions.TikTokCaptchaError: TikTok blocks this request displaying a Captcha
Tip: Consider using a proxy or a custom_verifyFp as method parameters

**Comment by JAVAB3ANS** [comment]
I experienced this issue as well.
